######################################################################
##
## Filename: tb_ComplexMultiplier.udo
## Created on: Fri May 03 10:40:09 PM Iran Standard Time 2024
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
