# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/intel_project/AX7010/06_bram_test/bram_test.cache/wt [current_project]
set_property parent.project_path F:/intel_project/AX7010/06_bram_test/bram_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/intel_project/AX7010/06_bram_test/ip_repo [current_project]
set_property ip_output_repo f:/intel_project/AX7010/06_bram_test/bram_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib F:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/hdl/top_wrapper.v
add_files F:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/top.bd
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_bram_ctrl_0_0/top_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_blk_mem_gen_0_0/top_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_gpio_0_0/top_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_gpio_0_0/top_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_gpio_0_0/top_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_10/bd_b43a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_16/bd_b43a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_23/bd_b43a_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_30/bd_b43a_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_31/bd_b43a_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_32/bd_b43a_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_33/bd_b43a_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_34/bd_b43a_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_35/bd_b43a_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_24/bd_b43a_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_25/bd_b43a_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_26/bd_b43a_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_27/bd_b43a_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_28/bd_b43a_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_17/bd_b43a_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_18/bd_b43a_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_19/bd_b43a_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_20/bd_b43a_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_21/bd_b43a_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_11/bd_b43a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_12/bd_b43a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_13/bd_b43a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_14/bd_b43a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_15/bd_b43a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_2/bd_b43a_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_3/bd_b43a_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_4/bd_b43a_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_5/bd_b43a_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_6/bd_b43a_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_1/bd_b43a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/bd_0/ip/ip_1/bd_b43a_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/intel_project/AX7010/06_bram_test/bram_test.srcs/sources_1/bd/top/top_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/intel_project/AX7010/06_bram_test/bram_test.srcs/constrs_1/new/top_wrapper.xdc
set_property used_in_implementation false [get_files F:/intel_project/AX7010/06_bram_test/bram_test.srcs/constrs_1/new/top_wrapper.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_wrapper_utilization_synth.rpt -pb top_wrapper_utilization_synth.pb"
