# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_wrapper.xdc

# Block Designs: bd/top/top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_bram_ctrl_0_0/top_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_axi_bram_ctrl_0_0 || ORIG_REF_NAME==top_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/top/ip/top_blk_mem_gen_0_0/top_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_blk_mem_gen_0_0 || ORIG_REF_NAME==top_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_gpio_0_0/top_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_axi_gpio_0_0 || ORIG_REF_NAME==top_axi_gpio_0_0} -quiet] -quiet

# IP: bd/top/ip/top_pl_ram_ctrl_0_0/top_pl_ram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_pl_ram_ctrl_0_0 || ORIG_REF_NAME==top_pl_ram_ctrl_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_smc_0/top_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_axi_smc_0 || ORIG_REF_NAME==top_axi_smc_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_rst_ps7_0_50M_0 || ORIG_REF_NAME==top_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/top/top_ooc.xdc
